---
- hosts: all
  become: true
  tasks:

    - name: install apache2 package
      dnf:
        name: httpd
      when: ansible_distribution == "Rocky"
    - name: add php support for apache
      dnf: 
         name: php
      when: ansible_distribution == "Rocky"
