---

- hosts: all
  become: true
  pre_tasks:
    - name: update reop cache (CentOs)
      tags: always
      dnf:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Rocky"
    - name: update repo cache (Ubuntu)
      tags: always
      apt:
        upgrade_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true
  tasks:
   


  - name: add ssh key for ahmed
    tags: always
    authorized_key:
      user: ahmed
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDCJKhYwc9M5LGisP1bfkWn/j+5AB9HEzebPT6hKc22SSe/X4PemrzDkQXNpyWQ90QGtl6IH8hFXgQx7oz2OweqlG7YgVqYwXcDrtvR33MONwMfUC6pvOnwGHBSoKaDmp3/ls7RyoiHbNyefRlUAJTYSKXtyQ4IO6QV4jU9t10OqjQTh/L2HwgUYxaEAQWpFUVNUVLDlu48gEYV2fT0uOeoHhuwyW00pKUc56A/T4m6jqHiS8BeH+YeKmCl1VLKQn8fD8URpUIpk26Ztaj3UdrI1EtYs/uCNJKRQ/iQEOFaNp+o9VzzyN0hOJFiR7kV4YPw+N9c8PZXix+wlEefwaZRJPY88YYvU3jmMVpxMzpke3jhyA1OOhHeFblWk6FaVtk3xyCkTnISy3N9WL2+8J/eJa6I4iKWdsFdnJ3yMgjJC3jjb6/8a9cyh8ONGCyFKMcrp44TufQ6OI2mBYf2bpcIn/KNTUs2o7n3TmQxIqox4iAMB/Rj2vyr2+fr8ZmNDAOge5IcjdIdkmXzS+sC2ARl40GHdQhHlD2xXBvO6xrsJFkcqRWhLH5pnJsNtSEdusSa2aDFOvodbGDHdXkaXskc/vyArffvOb0gJ5feIkD4pFhyrPj7T1xGUq9dMEc08u6WbuoRFolXSBDWMWV5Fl2bMcKK0htyCdEpcBLsVjEstQ== anwar@fedora"

  


- hosts: workstations
  become: true
  tasks:
  - name: install unzip
    package:
      name: unzip
  - name: install terraform
    unarchive:
      src: https://release.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


      # web servers

- hosts: web_servers
  become: true
  tasks: 


    - name: install apache2 and php package
      tags: apache,apache2,upuntu
      package:
        name:
           - "{{ httpd_package }}"
           - "{{ php_package }}" 
        state: latest
      when: ansible_distribution == "Rocky"
    - name: add php support for apache
      tags: apache,centos,httpd
      dnf: 
         name: php
      when: ansible_distribution == "Rocky"

    - name: install apache2 and php package
      dnf:
        tags: alah alah alah
        name:
           - httpd
           - php
        state: latest
      when: ansible_distribution == "Arch"
    - name: add php support for apache
      dnf:
         name: php
      when: ansible_distribution == "Arch"

    - name:   copy default html file for site
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        group: root
        owner: root
        mode: 0644

    - name: change email address for admin
      tags: apache,Rocky,httpd
      lineinfile:
        path: /etc/httpd/conf/httpd.conf 
        regexp: '^ServerAdmin'
        line: ServerAdmin anwar@localhost.net     
      when: ansible_distribution == "Rocky"
      register: httpd # can name pizza or any name
    
  #  - name: second change
   #   tags: apache,Rocky,httpd
    ##
    #   path: /etc/httpd/conf/httpd.conf 
     #   regexp: '^ServerAdmin'
      #  line: ServerAdmin anwar@localhost.net     
      #when: ansible_distribution == "Rocky"
      #register: httpd # can name pizza or any name
    

    - name: restart httpd (Rocky)
      tags: apache,Rocky,httpd
      service:
        name: httpd
        state: restarted
      when:  httpd.changed ## pizza.changed

      


    - name: start httpd (Rocky)
      tags:  apache,rocky,httpd
      service: 
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "Rocky"

      ## db servers ##


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOs)
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOs

  - name: install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution = "Ubuntu"



- hosts: file_servers
  become: true
  tasks:

  - name:  install samba package
    package:
      name: samba
      state: latest



- hosts: group_anwar
  become: true   # this for sudo 
  tasks:

  - name: first install fucker package
    dnf:
      name: fucker_package
      state: latest
    when: ansible_distribution == "Arch"
